table Sales
	lineageTag: 7bf91e56-78eb-4897-8020-e83aedbcbf23

	column Month
		dataType: string
		lineageTag: 81445074-0c9a-4c52-b1b9-5a5c5a14d809
		summarizeBy: none
		sourceColumn: Month

	column Country
		dataType: string
		lineageTag: 4dcd1581-53b1-431f-b37b-fa85f609220e
		summarizeBy: none
		sourceColumn: Country

	column Revenue
		dataType: double
		lineageTag: 60daeb8e-7815-41ee-be25-9c5c9dc5a016
		summarizeBy: sum
		sourceColumn: Revenue

	column Orders
		dataType: int64
		lineageTag: f83a9458-f391-47b9-b242-b266ede1efb0
		summarizeBy: none
		sourceColumn: Orders

	column ActiveCustomers
		dataType: int64
		lineageTag: eac079b5-4a71-41dc-94e8-a7cb8d8fa738
		summarizeBy: sum
		sourceColumn: ActiveCustomers

	column Units
		dataType: int64
		lineageTag: 307848cb-c799-47d5-bc96-df4a86b029a8
		summarizeBy: sum
		sourceColumn: Units

	column Year
		dataType: int64
		lineageTag: ff646656-de75-4210-94a2-15a345e8872f
		summarizeBy: none
		sourceColumn: Year

	column FirstObservedMonthRevenue
		dataType: double
		lineageTag: ee170d3c-2930-4b35-ae9c-6681993b24a9
		summarizeBy: sum
		sourceColumn: FirstObservedMonthRevenue

	column ReturningLaterMonthRevenue
		dataType: double
		lineageTag: 17695d68-993b-4f80-a5f8-07fbd7aa788f
		summarizeBy: sum
		sourceColumn: ReturningLaterMonthRevenue

	column AOV
		dataType: double
		lineageTag: f27fa55d-267a-485f-97ba-6e189c3de664
		summarizeBy: sum
		sourceColumn: AOV

	measure 'Recorded Sales' = SUM(Sales[Revenue])
		lineageTag: 4753fc15-dcfd-486a-93de-68fe0b478596
		formatString: £#,0

	measure 'Invoices' = SUM(Sales[Orders])
		lineageTag: c234ce5b-a284-4e9e-8c6e-862554870a74
		formatString: #,0

	measure 'Average Order Value' = DIVIDE([Recorded Sales], [Invoices])
		lineageTag: fa13dec7-61a5-4d0e-b63c-7c90e8e84f41
		formatString: £#,0.00

	measure 'Later Month Buyer Sales' = SUM(Sales[ReturningLaterMonthRevenue])
		lineageTag: cf560fac-a5d2-493b-82d5-bf0a93c681f0
		formatString: £#,0

	measure 'Later Month Buyer Share' = DIVIDE([Later Month Buyer Sales], [Recorded Sales])
		lineageTag: e7b37bc0-e911-45d6-a2c5-cdea2d14b04a
		formatString: 0.0%

	partition Sales = m
		mode: import
		source =
				let
				    Contents = Binary.Decompress(Binary.FromText("H4sIAAAAAAAC/21b244cR3J936/QB/Q28n555MpaQ7bkNSTsAn5skW1xYHJIDIdaSF/vc+KSWTWzkIDqyWBUZWVGnjhxqR8/PT6/v3z76evj89Pvl5/uv90fv94vf3t6d3/6cnnz9vnht/u3X788f/rIv//++PD85fI/99vT5a8PT1+e//bLl/vTb/d3P/ImrvvT/fnr0+PD468/3J7vTyfRm7/9408pxPDnmC5vcNen24eH22WOeW31ki/pkku/8B/4WLiGcMlpXsc4K0It1n5N4RLxXxmqZUOipb+X1l/uH359+PrxEktu1x4v9VIuMY1kijYqmmn0ay5L89v3t8fH+4dvvv/y4fb47sslx3ytWZ7bp6rbkM5Wfm/t3z8/ff1yibnVa0qqVe0lfVDnq38sxX+7P368Pf3fJQZMJ+p75tRM0wZVU/9Ymt99/9N3lxFDvia8Ixc2l1FV0YdFsZZwfOJfHx75hpfYsi9snL5AOqbPk99b7en2+PaOO6d6LdhELv2llBH8iTouqiW0a+pL9d/vTx9vj7/j3fkKvVzSvMRxaaUEXyETqHaN17wf/P3bu8y3x3jFTsgCRdsRGxM1/b3Vnm8ffr+0Gq4VT+F/055mY2Z02I26lP7j9vn2eEkVexSjaMWUs6r5qC4ObOpat+IPD8/vv94eaa+txWtotDs8aa2rDur7RTyzLdX/uj+/vz+p0cUeh9gmlGuLpmyDojzqxGUrf3r65+33S86Yzmyih8Wxc+Kjtp0zXss+X//9SVY1lXGNTa3At8PG9JTI74PW0/PXX28f8A9Lv85+afhvdle0QV3agm3cJ+Tnz7eHRxpxvvZMY72UlpaZy6CqYaXSPpY///P+7v4o0+hqrPMwyx72LHs4KD08/6Frip1K5TrFAGAi/kQbFOUW07XsVyT63d9985+AtnefPmI+ucxyrZGmACubsiFrZ7dYJzLrtcpZi38O8YB+ac5+DfnCFYupFWpjf/nsjLM7yrWNS0lY7Lq0F5gFjOcmi9Z0k3hm67XBHnK6dohKMuMXzZdg1jqmNWT5Up16AxvTJZDfW13RrGI3qyFEsRnbmAELfy8tASRgEPav4z1hi6UP1TKDUFHBSuS9Ro5HGUg+9ajGaE/LWZ6WwrVw2cd17tUxQIrQG9cBBTwS65uKPbONADXATO+yejXgMOzHLlCqMU6uZMbajMtoiqGws9lw33qpEXjRgXWEqLz1n+53PD41sVdZpKq4HdegmkRbFi2KjmcFa54dz+phnUygl60meJZCazQ2mkKMwbbSR3UvB5dj6f1w/+X2+OmR5z/Dv+rzhk3UBx0hsnlg0TwCU62AdM6N+1N6MnWsHFa44n6wemxFb0eDMIhpcJXmE9M4GoQJ9HLQMojJKWH3sRDE0jbrmnIVq6ywfCzAwMTmfubPOLa3z5+eYBgTPjCL8V6GEo64BvWF9Y+tKxDVEt5idjmpQPlsdh9xREfHWZyJLnlMMomtqjA1AAUCwwln2Q5q5ilpclhgxIWXcdDbSJVr7Nx47m2qw9RTCTjoeHCkf+PZ6A5XcocXcJV6zgV+CguTYfuwaMD6KGYoQJ5J5CMVapjhFZ4YbAP/3O53JGxYB4BTEQ7VYjts3JJUTKWfVaFYshy4JEzPXsPGVB1mE8dSWzA3MZPQL+PCZV7HsIH11MusQ1AcXKa3pfoK59r2ZtOM1MbU4pp7M1VXnMtEpJHV0LDcbmj6yIiFvE7YUC973aH7x/3t+29+un/++suHh7fY3gmnrqerNMdKGTOsnOb0RdtpX277bCSbsI2ZNzycDeN8nRPCG00hNem4MS4aPWDKS21TvvrC2UcfMwSox+UxhO0FuEDPiX9M9M7DUQ7vVLFoo2R6klzbdey5OsD2kvN1Aq4m1TNopb1mKI3vCcvoJOUZ/OSwQt9/ebrdP1x6n06Lk6OWjekby++tpSiZhDDJe8ZwNFwV6GUpGeubtRJQxAGFGs1uATad3HEKwpWOw1yW5hEiC44sLbVSf7o+YaPgBGWgFtjKjDDxvPWVvtUZ3PWl6Y5WxxarKHVpOa6GcqWxilZfnoc+i34T+JPh8kI66BmyxhCXr60+0wQqkirwtDIkq+HgbMGobl/fPXzz5un2CykuFmWq0TpK2ZBakfzeqkr8ekqEbZ6xUd39FLhGMqmGdwX9yeHaDoqKqaVNZyHJcczG1F3K74PWRtTEG2OKRDB4c3tPG7RYIx0t3sCU7/nNdx8fnhDafsGhWh4+VzujNmaH7uDfX/FHIG4J+Af5QhRu4iZxhtwfpUjOnAnTI9csmxcP/CgfALkUOMSpzr8n33H4XmxbiaDbrdFCsfr9rA3dGiUgFOP25bcxNTEc3rYf6picRpWtgTuhnu92x9FFOIPDJTQah/rax1L+9vZ4e0czCYQHMZPhGy5DZiZhH6X8Ov6uOHJZIwUukoGGjeodwAVOz1U4H1i/opF7SfNw+k2gl6W1oDiQWFRlcnE6SOmggrH+sTQFjREVMF7txLcMCujHycJEEzLmDHtXHJDLAOIiDCpCzJNjjo3aLbC4JWxVBeU5CCywgUpUrRbZ4AZMTCAg6BUuQFAVLHIv0WK9ESPXgSkHsuZW5wZ1OGrGmTBGkK/c8/HpxnoJ2Uat0vCl0jFdKfm9tBSVYwOxGmq+bZgXiHmKWupyoit97jYKRWbMCGClhuAGyE3JkbETlifvCR4RuYUg6aVB2hqKrRBOimBCBVfDaevYoLSn6gE1MCxwqpEBwimIEUFEDB/2Uw2ReXK7UuzY0lFLBXo5aHkwXbpAuRCQ6gFMHKA+cJwNDDeSJg9w/KWssFoQyeorUqnbKYm1St5IUhZVQhgLxVVVgZU3jOZ1SjvxchHA3DGpg9YxqAZUT/U9rXXHRPg/EASGS6CeeGbZ7/oyqq6JiTDYDiwRlA8+No4DT4VXgo9upHE90Zlx8fCmDtXlCIspMn5TDlWOgZQK9HJWJCLiADE+JUsNx7DEBSD6K/4qm6V2xFcMKxnIx26I6IAIK7vS0CYIxti6T7c/Hj4wrM0+07x8oA0aoskfS/ElKCaIjdhMjzV1yNIgeVtlUXyqlbEhb80XjSdAdJkEd3XrfX369Pl+e/zm208fP37FxjFKrhKCS3Zy7RGHLAtbN0qUBW9cqpnErMsMJ56q1BpnP+WtptCWW1F0kf9TSE7ImXPj/Gk5cLQZ57/2pb2gLQTQHoRq5NWIHmddTJe0D/ifcdoGplSZdNn6Cm10MF29VnJ/Z2O6ZvJ7aXk0zxC4VWMp+Xj0VaCXrSaIWBBEZmWcgAbbzz6Y0kyAiqaJrbQX1phqw8wtGzbm0XRdYteldwrlh3DDJC4nnOxeBfNkgk42kxJgGkA7aplALwctp5oNQV1VpBj9aHwuGWQhexsOAXwHUhv37+P4zCXR69ZVqtlK1UpDvswFpnwtZtpA+DLDsbE9eVmIWKYjYg7No7EmYyNrvric9Q6YmCd9l2KiJ758UJdqzh0ul8vff34Ds8jEUfEYzgltzKwnbxpeXqFoqAjM6VPnnPBkkxFcnyuBNQCZkcaI0EQSjFDY1Jy3+/L5/vbhfx/u75ig3IGWk4m5Ay39bar1CL8zFz6Fb47XPWWyTMQkulVLtjIDiYAF52lhvqSbm51JoknWE5h9w4L3tDT/cnv/xD0mVS6WLNzcMG9AAtXoe7aLziIO47GaTDH04k9UqoRoZNAjpR43V6uvMHjC5iwcSOl40k2gl6Xu9LKA4NiZhUmd0n0i0MtSU25ZIjAOMWUcwi1PXnoJ+wActqXpedFC22FeszE1Oparqg2oC+/BTOe1FTDEuXl43TA6SC0GyxXUn2u1WkhBeDJYuUSMCEt2lFkN2ggmxfDQCcJCGQj0spQU2GIA2wzVHKRzARu0Ipj8sfSOwAYfHK5Yoi50L5edeIKz6AFvU7BtAc5jcbDq8IZgJJGnCzeNtquF3LldZuikfAVsrLSDoiFco7fJlsfda8QxPfXye+kpRiVuArkJKWYpZwxXUWO+aRuEF0L0SPLMzFNKTsfnyYhO2cWM7Tb2jVDfjmkmMyTVwxFgiUNY177BC7yRTGIVipvht2bWLfJU3ajgL8Jzcd4RFEvIVDcRqifAGUDipmQZ3srvIGNW6UrbPbcD4NSK0EVqSEzO+cMjkx3gJiUSZcmemXaKS98hILMc0JKzi51Dl0pyo1uKUmxhUmure0yLkJfxsOY+nG7boFE4+WMrvqRwAVYa1F5GPm2hSey672C15cjQN53Zoz3SJHpdig49aZLQq0MELORVQCqsa8wmsAmevYG2Gf7kGCQXLpmDFvoptnVhLYxPtuZr9shw0I51TP1EjkSgl3UHp48ILZk5FzV/YRuzCj5/bzUDvkQr5LZORsdt+HEGok2JOEJC6JeIbIeKTjvExvSbjN8KA07cYAVk5GtAeGbxEJEUlgLm0t9UMDlViqczagK9bDUr7CTmvjUjdzIKGY8w+VCWzo+3D883YFpm6laKvk4DbUyfh9C2bks8kcDWu/BVtkgk0EWDA0APfG9Ng+kKxI1t1yPbylbGwAK2nr/piQcfNffLI7o1vdgMU2vKBZ0KJsAzh6qZ1M4gtw2xUsnT+mfxzWBZJGt+g9Wz1o6aBrIdG4wdHJK8irvmdWW8RwoI08hkBHumzgS7lLsk/TQ9wRGlb4DRB3lzOsTU7QS1lc5kauEKcvcm9DwMepic5ZZmqSuuO7zkdiV0PKKzzsfqAzx1HGkleuuoiKGqlKjAHBl4MxMYxuF+G2sB0Z6YOJVkfXwcfGI/loBYvAoMdTNLMseUhouYto8vdB9uWq6yDEF13PBBCz7rxsm+KRoLbM06d1ZUJNBGnjuMk4x9hPoCZwmalJrhkJ8g0kV6XZor+VfHInXlGGqYQC9LTdGxTb4OYzUsD2y0nKIbEzKfvuyk/yt0FApvzDDHUx5GBHpZd1joGGHz1koByOor4AiMKXsXqGLW/TDv1cTDzFKVCHmw0OzKoQQ6kg6UvjbcuEfr4xHtBZAlgWpPLZk3xtOeuCxsZxjYpSJ5/VLnceaePExxr/UpS6YCvSwtKwRFVge6OpGW84kIm0SvW1GzjmX1VaV00tLx0ndY0z3AJlcKlsgL+Wz2KrLrUjx18UQyTknSnLy0jMbNlbsjameNU1sBajYotjFNl8jvpbXqP53cTfJ345S/U0EOeSNbP7bu0P0ZHcgvKIiK2jF/1Q8xeW6EaCut9XRq7zCRXbeyEV51fhJ51eC1cdgLE0MZmNwsbda2pmJxZMNU0c7BenKOLkHsuNG/n0tAzKWH6nBi2kw9sCZB7yPpcwQVcem/QuLEpIx4S5YPmAebDSTBkBjhXJAodgxmTmllpKDtcL+NxH1K9lDexVNiNubdIrsgNY5QDHbNAEZD3niKGEzEc7k53NhYzLbHoKnO7qWYCYKOo1o0YSQtZmVpLrLMIk1IUv7ZGXQ23LC6XluUWKQwbF66BsbkHs3aYpwhLOYmP7fGy9JPaRJGSHCUnKD3Kswv9SDdlAMLtTJjY/dRKh9QMO27VSp6ACm/l9qB5gr3J80tubyiuYQ5di3sJVo19TAlh8odbadjuCRCGLai0dRQqmw7/RRUd0J4SqMB7GwUrn2RKHupLxBu7PnC4lh8n5vXcYu1bWV2o7B/ph5ySGPRVKa5p9Vwen+R/57RLltNYbiklrwvNmVvBPJRS7vLH1tTcXjQxLpuavBkhFQQATg9Zpxgsca6DVhpLv711KZIcmfP2QTtAsLJZQI7z+MSn4pAU8+ulNjOkbaLYi9llxaGozJgSiJmSeh5pkd68TqYXRcS12va3Udj1YGaIKEcVY9PbcxoVzhrebI0wfVZmv0VgTGRXpeuoesoUhmeLErUUxHERazRlr0phq0kwUOZdfa1QQTNCmJMmhBkD2k96G1sLSNJqC2hePcaio8aDQoHCjBel4ECs0xR8jKDXAnmP1Y6oMLFNHEQc5DoCznoO5syTtBa4XdCPq+6GrQJ2qE3cx6hFQbAUEB6M+Mpg+ki4f5z6S58bEGSCVIMaoubB6kvZDZhsxIWiM5L9yXaRZAgCWGklnZi5yZhRmJ547nyAQxGHemOWjYul6W0iC7bLLvu+Dg9zSWRXX1pawpEIlpiZmjKo4hs80SKXNqZRupL1TES4KYOPO/+lkieyn44jd/iwYNPx0hg/+jSGUIGLoF59WAKXM+6ATuLPXIew7rBpqoTmwGIpJlG5ma9zh3pYybzEcSOLp1WB+uwqLxPZzvnHJ2O62XpKHlEVGdtlo6OOmLVo91hOU84NciZ85DG2RxPLshFkfFz2DtjONW4eFBoDOXHagQYU3rjEVJMSdeGXHcr2XSoKoObrSSyHvfUBYTGo5ZDVcaCw2+JHc0VfOigtdbMnUafXq8uZbKLkfXTVN1lRT6MZfYJJoVoqtZ2nKpjFaNqTdHmE/8xAYOaheLzHJFnIH3VVsZUT8kzF8HL1N3ROf91K9Bkn3Qxe/Ayi45pCUB+v7yHox0ezO4MdpEWJgIi++FCy6vjEDaZpFxUsvR3TIZgCHjtpYDGhywoOxGyZUHPfS4uiuxM8rjelfklTsqeDSinhlwT6GWpOdgVRgU0Q4lrcj1yBpexQynmpfq6fs3kaLJaUT4hrYmYLu+HOyjYFfZQZeuQyN6dwxQIVjMzX1c4sRDskx7VPbdokvp1y8udy4kmmJs9Q9sRcyRJFqqLXHmyKDWbLD1tCT7iMGXllBPgJb1RQfsJ+4lUurQx4N6qi1TOKT0fjFvIOFbmip1hEiYx0EKUkfZ8nVe2CTEBjX11l5nj6txHWMgoIVambLK4Re98gb5DZqrAWRJQdtgMiaq9YzPyeLN8MIt0tJW6q2y4gzPLyPyqZapbP7MYk+h1a1qMn4d6cBYvHVJkyPjaip2pIwidmbtqU8Av5rm6ihgxFyWdbICRdpWlalE+eIpni9YHGTpmzaJzpYqgdCKVoNsCOZGmnD1D0KX5Eq8cpGEHbrse9K2zKLBpetqXaV6H0SYvVpkbOX2TVONSXahbWcWC2SBkpZPwxhtpw+bZC3SzzHrWDRk//fyGPRHJG7byak21QQtW5I+ltUN+MC/fzJSPZ94EetmK2kQ/qhBL+rOch68uE+dsKpsgNtr2A9+8VQ3nET40y2ucGIoLRlwdX6K1cb51WGjucm4QhniOmSWOJsFDlkRRZrtKX3dgIT5lONFknL2vZgwbtQROras4RrUX6D4aIy1aXUuSaWSCrMYcVu89+7CCpMUmEw9JggIvncTj50KR2VEWZyVPcCKFJqlxdzC4KhUJLNbW1P3oN1pN5gzFPklP59J0eK+VzRTkfwz28SqnRiGVsfKWtuorKiuBe5dZ93jO1KgE/mY1ecf1oRELt8M+hfHUkI2ZdwnHGa+6Fhsqarem1pNtuoi9ttuX2TdK2FXMpjC1Lx8bhRRPGT6T1om4ec91YTM7bGGGtLKWxzmlKBLs/KKFcX2ohKiYffTM516s39epME8soatU3IAtdBKwrBssZIZDb2wvY8eoFGsXmeZngaw5zakBk7Sd7hUzrGxDYkiph6ypxz41pTeG9EZwseNeMcPK3pq3rvUczt+CiMSuS09j98RmuWzpwnkKS4flzFZUGl98clRykeg8S1fkGQlMxjpA2IfAC1S5Fp5D6cUvo5yokYqYgVhxZFyfKkX5+lBjyFnO1U6VtLF71OPhYyU4AVn4qR+veI8cI7jCkiP8XZGP7xZFjf7BEcJF+WooSlEarLg4rA9pCmVdZzLHAnSPW9eTo1X6gPmu00NXeHD6RKKsNDKeTs8RLzuDg6G8GC/g8crENDkbhLdCjArw03vK46tPjuDuGiJdds5ktsYWnnOEG+srsVBzEnmrWllksBk2eu0vh2ra3ySX076pQC9LbfVk0oy6fcAT5ikaNlFmmmEszVfIxRSsPridqaGOy2Vpr2Rjll5p/c4kbcKS3WPI76Um4NNaE7Y55Tu805lwUQcpXMRjf73DtFrXz6q2U+E3IHQKQ0J3dkTvlzTgaYkfHw/2iTPgqN6eKLZZmJ4Y4mraabIOOpUfrk75docOq1YvNDO5yP4sbL2E52kF8NS2Zkp+CjKNO/iXdDpm55i/l5YTSH6dO9L5My6jZCLQy1azCnrwjqNyrqDLuF6WzhFpMtvQelHeeerNcglzaog0trYCTZIe4WIxWDyl3UzU4UtiXIobL4BoXiN+lXNSEZOaac/YM32DEbKQo+5sF/jB5mNcmPoupyd631Ben0Sd6ps2rpelREZEt9C03lD8TMCtEqkqO6qH1N4P2/DywxdibGYNC6yMiUa+Z1gf0LD0IyX5zGAqMKYnwP7p/wETB6ukqkIAAA==", BinaryEncoding.Base64), Compression.GZip),
				    CSV = Csv.Document(Contents,[Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				    Headers = Table.PromoteHeaders(CSV,[PromoteAllScalars=true]),
				    Typed = Table.TransformColumnTypes(Headers, {{"Month", type text},{"Country", type text},{"Revenue", type number},{"Orders", Int64.Type},{"ActiveCustomers", Int64.Type},{"Units", Int64.Type},{"Year", Int64.Type},{"FirstObservedMonthRevenue", type number},{"ReturningLaterMonthRevenue", type number},{"AOV", type number}})
				in
				    Typed

	annotation PBI_ResultType = Table
