"""Four-page decision-oriented PDF; all reported figures from results/*.csv."""
from pathlib import Path
import json,pandas as pd
from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.platypus import SimpleDocTemplate,Paragraph,Spacer,Image,Table,TableStyle,PageBreak,KeepTogether,CondPageBreak
from reportlab.lib.styles import getSampleStyleSheet,ParagraphStyle
from reportlab.lib.enums import TA_LEFT,TA_CENTER
ROOT=Path(__file__).resolve().parents[1];R=ROOT/'results';CH=ROOT/'charts';OUT=ROOT/'report'
M=json.loads((R/'verified_metrics.json').read_text());mon=pd.read_csv(R/'monthly.csv');seg=pd.read_csv(R/'segments.csv');co=pd.read_csv(R/'cohort_retention.csv')
N=colors.HexColor('#111F30');MUT=colors.HexColor('#51677B');TEAL=colors.HexColor('#139F91');PEACH=colors.HexColor('#E5855A');PALE=colors.HexColor('#E9F5F2');BG=colors.HexColor('#F4F7FA')
styles=getSampleStyleSheet();styles.add(ParagraphStyle(name='EyebrowR',fontName='Helvetica-Bold',fontSize=9,textColor=TEAL,spaceAfter=11,leading=14));styles.add(ParagraphStyle(name='TitleR',fontName='Helvetica-Bold',fontSize=28,textColor=N,leading=32,spaceAfter=12));styles.add(ParagraphStyle(name='SectionR',fontName='Helvetica-Bold',fontSize=17,textColor=N,spaceAfter=8,spaceBefore=12));styles.add(ParagraphStyle(name='SubR',fontName='Helvetica-Bold',fontSize=11,textColor=N,spaceBefore=11,spaceAfter=7));styles.add(ParagraphStyle(name='BodyR',fontName='Helvetica',fontSize=10,textColor=N,leading=15,spaceAfter=9));styles.add(ParagraphStyle(name='SmallR',fontName='Helvetica',fontSize=8.6,textColor=MUT,leading=12,spaceAfter=8));styles.add(ParagraphStyle(name='MetricR',fontName='Helvetica-Bold',fontSize=19,leading=24,textColor=N,alignment=TA_CENTER));styles.add(ParagraphStyle(name='MetricLabR',fontName='Helvetica-Bold',fontSize=8,textColor=MUT,leading=11,alignment=TA_CENTER));styles.add(ParagraphStyle(name='CallR',fontName='Helvetica-Bold',fontSize=11.5,leading=17,textColor=N));styles.add(ParagraphStyle(name='TableHeadR',fontName='Helvetica-Bold',fontSize=9,leading=12,textColor=colors.white));styles.add(ParagraphStyle(name='TableCellR',fontName='Helvetica',fontSize=9,leading=12,textColor=N))
P=lambda s:Paragraph(s,styles['BodyR']);sm=lambda s:Paragraph(s,styles['SmallR']);sec=lambda s:Paragraph(s,styles['SectionR'])
def pic(name,w=470):
 from PIL import Image as PI
 fp=CH/name;im=PI.open(fp);return Image(str(fp),width=w,height=w*im.height/im.width)
def block(s):
 tab=Table([[Paragraph(s,styles['CallR'])]],colWidths=[493]);tab.setStyle(TableStyle([('BACKGROUND',(0,0),(-1,-1),PALE),('BOX',(0,0),(-1,-1),.7,TEAL),('LEFTPADDING',(0,0),(-1,-1),15),('RIGHTPADDING',(0,0),(-1,-1),15),('TOPPADDING',(0,0),(-1,-1),11),('BOTTOMPADDING',(0,0),(-1,-1),11)]));return tab

def header(canvas,doc):
 canvas.saveState();w,h=A4
 canvas.setFillColor(N);canvas.rect(0,h-52,w,52,fill=1,stroke=0)
 canvas.setFont('Helvetica-Bold',10);canvas.setFillColor(colors.HexColor('#73E0D0'));canvas.drawString(48,h-31,'RETAIL / INTELLIGENCE')
 canvas.setFont('Helvetica',8);canvas.setFillColor(colors.HexColor('#C0D0DF'));canvas.drawRightString(w-48,h-30,'DATA FIELD REPORT   /   HISTORICAL ANALYSIS')
 canvas.setFillColor(MUT);canvas.setFont('Helvetica',8);canvas.drawString(49,33,'Filtered extract  ·  figures assume GBP  ·  descriptive analysis')
 canvas.drawRightString(w-49,33,f'{doc.page}');canvas.restoreState()

pdf=OUT/'executive_field_report.pdf';doc=SimpleDocTemplate(str(pdf),pagesize=A4,leftMargin=48,rightMargin=48,topMargin=78,bottomMargin=53,title='Retail Signals | Revenue and Customer Behaviour',author='Online Retail Analytics Portfolio')
S=[]
# P1: central question and proof
S+=[Paragraph('QUESTION 01 / THE AUTUMN SALES JUMP',styles['EyebrowR']),Paragraph('The revenue grew.<br/>Did baskets get bigger?',styles['TitleR']),P('I began with monthly revenue, but that alone did not explain what changed. I compared distinct invoice counts and average order value before drawing a conclusion about the autumn increase.'),Spacer(1,9)]
metrics=[('6.07m','Recorded sales*'),('17,635','Distinct invoices'),('+34.1%','Sep–Nov sales'),('-12.4%','Sep–Nov AOV')]
row=[Table([[Paragraph(v,styles['MetricR'])],[Paragraph(t,styles['MetricLabR'])]],colWidths=[110],rowHeights=[32,24]) for v,t in metrics]
t=Table([row],colWidths=[123]*4);t.setStyle(TableStyle([('BACKGROUND',(0,0),(-1,-1),BG),('BOX',(0,0),(-1,-1),.6,colors.HexColor('#D6E2E9')),('INNERGRID',(0,0),(-1,-1),10,colors.white),('VALIGN',(0,0),(-1,-1),'MIDDLE'),('TOPPADDING',(0,0),(-1,-1),10),('BOTTOMPADDING',(0,0),(-1,-1),10)]));S.extend([t,Spacer(1,10),pic('01_monthly_sales.png',477),Spacer(1,6),block('September to November 2011: +34.1% recorded sales, +53.0% invoices, -12.4% average order value.'),Spacer(1,12),sm('This is an arithmetic decomposition, not evidence about marketing campaigns, prices or causality. December 2011 ends on the ninth and must not be read as a full-month decline.'),PageBreak()])
# P2: understanding first critical data quality steps and why results depend on them
S+=[Paragraph('METHOD / THE DATE PROBLEM',styles['EyebrowR']),Paragraph('The dates changed the story.',styles['TitleR']),P('Before comparing months, I checked the first invoice dates. Invoice 536365 was recorded as 2010-01-12, but the expected sequence for this source begins on 1 December 2010. Month and day are reversed on rows where both components permit the swap.'),Spacer(1,10)]
rows=[['Check','Observed result'],['Rows in supplied filtered file','384,721'],['Rows with day/month swapped','147,998'],['Invoice-date inversions in invoice-ID order','21 before repair / 0 after'],['Invoices with multiple corrected timestamps','30 (use earliest for invoice date)'],['Exact duplicate rows','5,178 (retained in main figures)'],['Exact-duplicate sensitivity to sales','23,119.37 (~0.38% of reported sales)']]
t=Table([[Paragraph(x,styles['TableHeadR'] if ri==0 else styles['TableCellR']) for x in r] for ri,r in enumerate(rows)],colWidths=[290,203],hAlign='LEFT');t.setStyle(TableStyle([('BACKGROUND',(0,0),(-1,0),N),('ROWBACKGROUNDS',(0,1),(-1,-1),[colors.white,BG]),('VALIGN',(0,0),(-1,-1),'TOP'),('LEFTPADDING',(0,0),(-1,-1),10),('RIGHTPADDING',(0,0),(-1,-1),9),('TOPPADDING',(0,0),(-1,-1),6),('BOTTOMPADDING',(0,0),(-1,-1),6),('LINEBELOW',(0,-1),(-1,-1),1,colors.HexColor('#D3DFE7'))]));S.extend([t,Spacer(1,19),sec('What the order-level check added'),pic('02_orders_vs_aov.png',385),Spacer(1,7),sm('The growth in invoices is substantially larger than the growth in sales value because average order value falls over the same period. This does not identify which customer or marketing intervention caused the movement.'),Spacer(1,10),block('I kept duplicate rows in the headline figures because repeated identical line items can be legitimate; the separate sensitivity result shows how much removing them would change the total.'),PageBreak()])
# P3 cohorts
S+=[Paragraph('QUESTION 02 / CUSTOMER BEHAVIOUR',styles['EyebrowR']),Paragraph('Returning is not the<br/>same as retention.',styles['TitleR']),P('Of the 4,261 observed customers, 2,773 placed more than one invoice during the extract. This retrospectively defined group contributed 92.1% of recorded sales. The percentage sounds striking, but it cannot tell us what a new cohort will do next month.'),pic('03_customer_segments.png',465),Spacer(1,9),sec('Follow-up: first observed monthly cohorts'),pic('04_cohort_retention.png',455),Spacer(1,6),sm('These rows are customers first observed in the respective month of this file, not confirmed first-ever customers. A cohort’s month +1 rate is the share observed purchasing in that exact later month. RFM segment labels are hand-set descriptive rules, not a churn model.'),PageBreak()]
# P4 implications and geographic context
S+=[Paragraph('BOUNDARIES / WHAT THIS FILE CAN ANSWER',styles['EyebrowR']),Paragraph('Useful patterns.<br/>Clear limitations.',styles['TitleR']),P('The United Kingdom accounts for 84.4% of observed sales. The international view is useful for describing this extract, but a geography comparison needs a warning: this is not a balanced, representative sample of global retail activity.'),pic('05_non_uk_markets.png',330),Spacer(1,9),sec('Checks I would keep before presenting this'),P('<b>Dates.</b> The imported year, month, week, day and weekday were calculated from the inconsistent dates. I derived new calendar values after correcting ambiguous rows, then rechecked chronology against invoice identifiers.'),P('<b>Repeated items.</b> Identical rows are not proof of a duplicate error. Keeping them leaves £6.07m recorded sales; dropping later exact copies would subtract £23,119.37 (~0.38%). Both outcomes are documented.'),P('<b>Population and timing.</b> Only positive-quantity and positive-price transactions with known customer IDs appear here. Claims about refunds, true acquisition, profit, customer lifetime value or returns are not supported. The source covers Dec 2010 to 9 Dec 2011.'),P('<b>Currency.</b> The extract has no currency field. Pound sterling is an explicit source-context assumption, not a fact encoded in the provided CSV.'),Spacer(1,8),block('If I extended the investigation, I would check whether the order-count increase was concentrated in specific first-observed cohorts, then compare that pattern by product mix. That requires more than one aggregate KPI.'),Spacer(1,9),sm('Reproduction: the README documents the exact date correction, SQL queries, Python pipeline, an anonymized Power BI starter model, and data-lineage caveats. The provided filtered extract is not redistributed in the public-facing project archive.')]
doc.build(S,onFirstPage=header,onLaterPages=header)
print('Wrote',pdf)
